# Generated by Django 3.1.5 on 2021-08-02 03:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JRSR', 'Junior/Senior'), ('ANY', 'Any')], default='ANY', max_length=24)),
                ('laundry_floors', models.CharField(default='', max_length=24, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('capacity', models.PositiveSmallIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('is_gph', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('floor', models.PositiveSmallIntegerField()),
                ('number', models.CharField(max_length=5)),
                ('sqft', models.IntegerField()),
                ('capacity', models.CharField(choices=[('SI', 'Single'), ('DO', 'Double'), ('TR', 'Triple'), ('QU', 'Quad')], max_length=24)),
                ('floor_plan_url', models.URLField()),
                ('is_suite', models.BooleanField(default=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='buildings.building')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='buildings.location'),
        ),
    ]
